### PR TITLE
bump telemeter

### PR DESCRIPTION
**Pull request by s-urbaniak**
cc @squat especially, if there are any concerns regarding the whitelisting feature.

### CODE REVIEW

**Review by squat — APPROVED** [review]
No concerns with regards to whitelisting; the integration tests are using the whitelisting feature exactly as expected. Whitelisting has been live in staging for some time now. I’ll do some quick tests to validate it continues working as expected and then give the ok here.

**Comment by s-urbaniak** [comment]
@squat oki doki :+1:

**Comment by jfchevrette** [comment]
This commit hash is now fairly old. What is currently running in production is newer.

I think we can close this PR?

**Comment by squat** [comment]
agreed. let's close

**Pull request closed without merging**
