### PR TITLE
telemeter-services: bump hash

### PR DESCRIPTION
**Pull request by s-urbaniak**

### CODE REVIEW

**Comment by s-urbaniak** [comment]
cc @squat @jfchevrette @aditya-konarde

**Review by aditya-konarde — APPROVED** [review]
LGTM, do let me know when we want to ship this to prod and roll out the change

**Comment by squat** [comment]
@s-urbaniak, can you also bump the prometheus hash? That way we can get the service affinity change in prod?

@aditya-konarde we should do it rather soon so we can start accepting a new set of metrics that have already been whitelisted in the client.

**Comment by s-urbaniak** [comment]
@squat ack, bumped :+1:

**Review by squat — APPROVED** [review]

**Pull request merged**
