### PR TITLE
telemeter-service: bump telemeter and prometheus

### PR DESCRIPTION
**Pull request by s-urbaniak**
cc @squat

### CODE REVIEW

**Review by squat — COMMENTED** [review]
Looks fine to me, but why are tests failing saying the manifest could not be found for that hash? Cc @jmelis

**Comment by s-urbaniak** [comment]
It seems the image is not being built automatically :thinking: 
```
time="2018-11-09T08:28:29Z" level=fatal msg="Error reading manifest f3f6d9a in quay.io/app-sre/telemeter: manifest unknown: manifest unknown" 
```

**Comment by s-urbaniak** [comment]
Also looking at https://quay.io/repository/app-sre/telemeter?tag=latest&tab=tags doesn't reveal the current master hash.

**Comment by riuvshin** [comment]
[test]

**Review by riuvshin — APPROVED** [review]

**Comment by s-urbaniak** [comment]
thank you @riuvshin ! :tada:

**Pull request merged**
